/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadproject.Vistas;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import universidadproject.AccesoADatos.InscripcionData;
import universidadproject.AccesoADatos.MateriaData;
import universidadproject.Entidades.Alumno;
import universidadproject.Entidades.Materia;

/**
 *
 * @author Leo Huari
 */
public class Principal extends javax.swing.JFrame {
    Color rojo = new Color(225,36,69);
    private Materia materia = new Materia();
    private MateriaData materiaData = new MateriaData();
    private InscripcionData inscripcionData = new InscripcionData();
    private ArrayList<Materia> lista = materiaData.listarMaterias();
    private int idMateria;
    private DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };
    private DefaultTableModel modelo2 = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        armarTablaMaterias();
        armarTablaAlumnos();
        cargarTablaMaterias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jpBarraSuperior = new javax.swing.JPanel();
        jpMenu = new javax.swing.JPanel();
        jpMateriasbtn = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jpInscripciones = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jpNotasbtn = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jpAlumnoMateriatbtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jpAlumnosbtn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jtpVentanas = new javax.swing.JTabbedPane();
        jpPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpAlumnos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jpMaterias = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jtAño = new javax.swing.JTextField();
        jtCodigo = new javax.swing.JTextField();
        jrbEstado = new javax.swing.JRadioButton();
        jpNuevoBtn = new javax.swing.JPanel();
        jlNuevoBtn = new javax.swing.JLabel();
        jpEliminarBtn = new javax.swing.JPanel();
        jlEliminarBtn = new javax.swing.JLabel();
        jpGuardarBtn = new javax.swing.JPanel();
        jlGuardarBtn = new javax.swing.JLabel();
        jpBuscarBtn = new javax.swing.JPanel();
        jlBuscarBtn = new javax.swing.JLabel();
        jPanelInscripciones = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jpNotas = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jpAlumnoMateria = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAlumnos = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtMaterias = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpBarraSuperior.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jpBarraSuperiorLayout = new javax.swing.GroupLayout(jpBarraSuperior);
        jpBarraSuperior.setLayout(jpBarraSuperiorLayout);
        jpBarraSuperiorLayout.setHorizontalGroup(
            jpBarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        jpBarraSuperiorLayout.setVerticalGroup(
            jpBarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jPanel2.add(jpBarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jpMenu.setBackground(new java.awt.Color(0, 63, 124));

        jpMateriasbtn.setBackground(new java.awt.Color(225, 36, 69));
        jpMateriasbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpMateriasbtnMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Formulario de Materias");

        javax.swing.GroupLayout jpMateriasbtnLayout = new javax.swing.GroupLayout(jpMateriasbtn);
        jpMateriasbtn.setLayout(jpMateriasbtnLayout);
        jpMateriasbtnLayout.setHorizontalGroup(
            jpMateriasbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMateriasbtnLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpMateriasbtnLayout.setVerticalGroup(
            jpMateriasbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMateriasbtnLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jpInscripciones.setBackground(new java.awt.Color(225, 36, 69));
        jpInscripciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpInscripcionesMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Inscripciones");

        javax.swing.GroupLayout jpInscripcionesLayout = new javax.swing.GroupLayout(jpInscripciones);
        jpInscripciones.setLayout(jpInscripcionesLayout);
        jpInscripcionesLayout.setHorizontalGroup(
            jpInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInscripcionesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpInscripcionesLayout.setVerticalGroup(
            jpInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInscripcionesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jpNotasbtn.setBackground(new java.awt.Color(225, 36, 69));
        jpNotasbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpNotasbtnMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Notas");

        javax.swing.GroupLayout jpNotasbtnLayout = new javax.swing.GroupLayout(jpNotasbtn);
        jpNotasbtn.setLayout(jpNotasbtnLayout);
        jpNotasbtnLayout.setHorizontalGroup(
            jpNotasbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNotasbtnLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpNotasbtnLayout.setVerticalGroup(
            jpNotasbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNotasbtnLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jpAlumnoMateriatbtn.setBackground(new java.awt.Color(225, 36, 69));
        jpAlumnoMateriatbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpAlumnoMateriatbtnMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Alumnos por Materias");

        javax.swing.GroupLayout jpAlumnoMateriatbtnLayout = new javax.swing.GroupLayout(jpAlumnoMateriatbtn);
        jpAlumnoMateriatbtn.setLayout(jpAlumnoMateriatbtnLayout);
        jpAlumnoMateriatbtnLayout.setHorizontalGroup(
            jpAlumnoMateriatbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAlumnoMateriatbtnLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpAlumnoMateriatbtnLayout.setVerticalGroup(
            jpAlumnoMateriatbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAlumnoMateriatbtnLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jpAlumnosbtn.setBackground(new java.awt.Color(225, 36, 69));
        jpAlumnosbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpAlumnosbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpAlumnosbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpAlumnosbtnMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Formulario de Alumnos");

        javax.swing.GroupLayout jpAlumnosbtnLayout = new javax.swing.GroupLayout(jpAlumnosbtn);
        jpAlumnosbtn.setLayout(jpAlumnosbtnLayout);
        jpAlumnosbtnLayout.setHorizontalGroup(
            jpAlumnosbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAlumnosbtnLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpAlumnosbtnLayout.setVerticalGroup(
            jpAlumnosbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAlumnosbtnLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMateriasbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpInscripciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpNotasbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpAlumnoMateriatbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpAlumnosbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jpAlumnosbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpMateriasbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpNotasbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpAlumnoMateriatbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        jPanel2.add(jpMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 768));

        jLabel1.setBackground(new java.awt.Color(0, 63, 124));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 63, 124));
        jLabel1.setText("ImagenPrincipal");

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(464, Short.MAX_VALUE))
        );

        jtpVentanas.addTab("tab1", jpPrincipal);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setText("Alumnos");

        javax.swing.GroupLayout jpAlumnosLayout = new javax.swing.GroupLayout(jpAlumnos);
        jpAlumnos.setLayout(jpAlumnosLayout);
        jpAlumnosLayout.setHorizontalGroup(
            jpAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAlumnosLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jpAlumnosLayout.setVerticalGroup(
            jpAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAlumnosLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(464, Short.MAX_VALUE))
        );

        jtpVentanas.addTab("tab2", jpAlumnos);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setText("Materias");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Código:");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setText("Estado:");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setText("Año:");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setText("Nombre:");

        jpNuevoBtn.setBackground(new java.awt.Color(0, 63, 124));
        jpNuevoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpNuevoBtnMouseClicked(evt);
            }
        });

        jlNuevoBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlNuevoBtn.setForeground(new java.awt.Color(255, 255, 255));
        jlNuevoBtn.setText("Nuevo");

        javax.swing.GroupLayout jpNuevoBtnLayout = new javax.swing.GroupLayout(jpNuevoBtn);
        jpNuevoBtn.setLayout(jpNuevoBtnLayout);
        jpNuevoBtnLayout.setHorizontalGroup(
            jpNuevoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNuevoBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlNuevoBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpNuevoBtnLayout.setVerticalGroup(
            jpNuevoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlNuevoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jpEliminarBtn.setBackground(new java.awt.Color(0, 63, 124));
        jpEliminarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpEliminarBtnMouseClicked(evt);
            }
        });

        jlEliminarBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlEliminarBtn.setForeground(new java.awt.Color(255, 255, 255));
        jlEliminarBtn.setText("Eliminar");

        javax.swing.GroupLayout jpEliminarBtnLayout = new javax.swing.GroupLayout(jpEliminarBtn);
        jpEliminarBtn.setLayout(jpEliminarBtnLayout);
        jpEliminarBtnLayout.setHorizontalGroup(
            jpEliminarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEliminarBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlEliminarBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpEliminarBtnLayout.setVerticalGroup(
            jpEliminarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlEliminarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jpGuardarBtn.setBackground(new java.awt.Color(0, 63, 124));
        jpGuardarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpGuardarBtnMouseClicked(evt);
            }
        });

        jlGuardarBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlGuardarBtn.setForeground(new java.awt.Color(255, 255, 255));
        jlGuardarBtn.setText("Guardar");

        javax.swing.GroupLayout jpGuardarBtnLayout = new javax.swing.GroupLayout(jpGuardarBtn);
        jpGuardarBtn.setLayout(jpGuardarBtnLayout);
        jpGuardarBtnLayout.setHorizontalGroup(
            jpGuardarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGuardarBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlGuardarBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpGuardarBtnLayout.setVerticalGroup(
            jpGuardarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlGuardarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jpBuscarBtn.setBackground(new java.awt.Color(0, 102, 153));
        jpBuscarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpBuscarBtnMouseClicked(evt);
            }
        });

        jlBuscarBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlBuscarBtn.setForeground(new java.awt.Color(255, 255, 255));
        jlBuscarBtn.setText("Buscar");

        javax.swing.GroupLayout jpBuscarBtnLayout = new javax.swing.GroupLayout(jpBuscarBtn);
        jpBuscarBtn.setLayout(jpBuscarBtnLayout);
        jpBuscarBtnLayout.setHorizontalGroup(
            jpBuscarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBuscarBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlBuscarBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpBuscarBtnLayout.setVerticalGroup(
            jpBuscarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlBuscarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpMateriasLayout = new javax.swing.GroupLayout(jpMaterias);
        jpMaterias.setLayout(jpMateriasLayout);
        jpMateriasLayout.setHorizontalGroup(
            jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMateriasLayout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addGroup(jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpMateriasLayout.createSequentialGroup()
                            .addComponent(jpNuevoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(39, 39, 39)
                            .addComponent(jpEliminarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMateriasLayout.createSequentialGroup()
                            .addGap(247, 247, 247)
                            .addComponent(jpGuardarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpMateriasLayout.createSequentialGroup()
                        .addGroup(jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel4))
                        .addGap(56, 56, 56)
                        .addGroup(jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpMateriasLayout.createSequentialGroup()
                                .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(jpBuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jrbEstado)
                            .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpMateriasLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(90, 90, 90))
        );
        jpMateriasLayout.setVerticalGroup(
            jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMateriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpBuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpMateriasLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53)
                .addGroup(jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtAño, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jrbEstado))
                .addGap(99, 99, 99)
                .addGroup(jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpNuevoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpEliminarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpGuardarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jtpVentanas.addTab("tab3", jpMaterias);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setText("Cosa de inscripcion");

        javax.swing.GroupLayout jPanelInscripcionesLayout = new javax.swing.GroupLayout(jPanelInscripciones);
        jPanelInscripciones.setLayout(jPanelInscripcionesLayout);
        jPanelInscripcionesLayout.setHorizontalGroup(
            jPanelInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInscripcionesLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jPanelInscripcionesLayout.setVerticalGroup(
            jPanelInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInscripcionesLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(424, Short.MAX_VALUE))
        );

        jtpVentanas.addTab("tab4", jPanelInscripciones);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel5.setText("Notas");

        javax.swing.GroupLayout jpNotasLayout = new javax.swing.GroupLayout(jpNotas);
        jpNotas.setLayout(jpNotasLayout);
        jpNotasLayout.setHorizontalGroup(
            jpNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNotasLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jpNotasLayout.setVerticalGroup(
            jpNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNotasLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(464, Short.MAX_VALUE))
        );

        jtpVentanas.addTab("tab5", jpNotas);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel6.setText("Alumnos Por Materia");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setText("Seleccione una materia:");

        jtAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtAlumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtAlumnos);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel17.setText("Listado de Alumnos");

        jtMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtMateriasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtMaterias);

        javax.swing.GroupLayout jpAlumnoMateriaLayout = new javax.swing.GroupLayout(jpAlumnoMateria);
        jpAlumnoMateria.setLayout(jpAlumnoMateriaLayout);
        jpAlumnoMateriaLayout.setHorizontalGroup(
            jpAlumnoMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAlumnoMateriaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpAlumnoMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAlumnoMateriaLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAlumnoMateriaLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(246, 246, 246))))
            .addGroup(jpAlumnoMateriaLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jpAlumnoMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jpAlumnoMateriaLayout.setVerticalGroup(
            jpAlumnoMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAlumnoMateriaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jtpVentanas.addTab("tab6", jpAlumnoMateria);

        jPanel2.add(jtpVentanas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 740, 768));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpAlumnosbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAlumnosbtnMouseClicked
        // TODO add your handling code here:
        jtpVentanas.setSelectedIndex(1);
    }//GEN-LAST:event_jpAlumnosbtnMouseClicked

    private void jpMateriasbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMateriasbtnMouseClicked
        // TODO add your handling code here:
        jtpVentanas.setSelectedIndex(2);
    }//GEN-LAST:event_jpMateriasbtnMouseClicked

    private void jpInscripcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpInscripcionesMouseClicked
        // TODO add your handling code here:
        jtpVentanas.setSelectedIndex(3);
    }//GEN-LAST:event_jpInscripcionesMouseClicked

    private void jpNotasbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpNotasbtnMouseClicked
        // TODO add your handling code here:
        jtpVentanas.setSelectedIndex(4);
    }//GEN-LAST:event_jpNotasbtnMouseClicked

    private void jpAlumnoMateriatbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAlumnoMateriatbtnMouseClicked
        // TODO add your handling code here:
        jtpVentanas.setSelectedIndex(5);
    }//GEN-LAST:event_jpAlumnoMateriatbtnMouseClicked

    private void jpAlumnosbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAlumnosbtnMouseEntered
        // TODO add your handling code here:
        jpAlumnosbtn.setBackground(Color.yellow);
    }//GEN-LAST:event_jpAlumnosbtnMouseEntered

    private void jpAlumnosbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAlumnosbtnMouseExited
        // TODO add your handling code here:
        jpAlumnosbtn.setBackground(rojo);
    }//GEN-LAST:event_jpAlumnosbtnMouseExited

    private void jpBuscarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBuscarBtnMouseClicked
        // TODO add your handling code here:
        Materia materia = new Materia();
        String codigo = jtCodigo.getText();
        try{
        materia = materiaData.buscarMateria(Integer.parseInt(codigo));
        jtNombre.setText(materia.getNombre());
        jtAño.setText(String.valueOf(materia.getAnioMateria()));
        jrbEstado.setSelected(materia.isActivo());
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(null, "La materia está dada de baja");
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "El código ingresado no es válido");
        }
    }//GEN-LAST:event_jpBuscarBtnMouseClicked

    private void jpNuevoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpNuevoBtnMouseClicked
        // TODO add your handling code here:
        Materia materia = new Materia();
        if(jtCodigo.getText().isEmpty() || jtNombre.getText().isEmpty() || jtAño.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "No debe haber campos vacíos"); 
        }else{
        try{
        materia.setIdMateria(Integer.parseInt(jtCodigo.getText()));
        materia.setNombre(jtNombre.getText());
        materia.setAnioMateria(Integer.parseInt(jtAño.getText()));
        materia.setActivo(true);
        materiaData.guardarMateria(materia);
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(null, "No debe haber campos vacíos");
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "El código ingresado no es válido");
        }
        }
        jtCodigo.setText("");
        jtNombre.setText("");
        jtAño.setText("");
        jrbEstado.setSelected(false);
    }//GEN-LAST:event_jpNuevoBtnMouseClicked

    private void jpEliminarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpEliminarBtnMouseClicked
        // TODO add your handling code here:
        String codigo = jtCodigo.getText();
        try{
        materiaData.eliminarMateria(Integer.parseInt(codigo));
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "El código ingresado no es válido");
        }
        jtCodigo.setText("");
        jtNombre.setText("");
        jtAño.setText("");
        jrbEstado.setSelected(false);
    }//GEN-LAST:event_jpEliminarBtnMouseClicked

    private void jpGuardarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpGuardarBtnMouseClicked
        // TODO add your handling code here:
        Materia materia = new Materia();
        if(jtCodigo.getText().isEmpty() || jtNombre.getText().isEmpty() || jtAño.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "No debe haber campos vacíos"); 
        }else{
        try{
        materia.setIdMateria(Integer.parseInt(jtCodigo.getText()));
        materia.setNombre(jtNombre.getText());
        materia.setAnioMateria(Integer.parseInt(jtAño.getText()));
        materia.setActivo(true);
        materiaData.modificarMateria(materia);
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(null, "No debe haber campos vacíos");
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "El código ingresado no es válido");
        }
        }
    }//GEN-LAST:event_jpGuardarBtnMouseClicked

    private void jtAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtAlumnosMouseClicked
        // TODO add your handling code here:
        ArrayList<Alumno> listaIns = inscripcionData.obtenerAlumnosPorMateria(idMateria);
        for(Alumno alumno:listaIns){
            modelo.addRow(new Object[]{
                alumno.getIdAlumno(),
                    alumno.getDni(),
                    alumno.getApellido(),
                    alumno.getNombre()
            });
    }//GEN-LAST:event_jtAlumnosMouseClicked

    private void jtMateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtMateriasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtMateriasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelInscripciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlBuscarBtn;
    private javax.swing.JLabel jlEliminarBtn;
    private javax.swing.JLabel jlGuardarBtn;
    private javax.swing.JLabel jlNuevoBtn;
    private javax.swing.JPanel jpAlumnoMateria;
    private javax.swing.JPanel jpAlumnoMateriatbtn;
    private javax.swing.JPanel jpAlumnos;
    private javax.swing.JPanel jpAlumnosbtn;
    private javax.swing.JPanel jpBarraSuperior;
    private javax.swing.JPanel jpBuscarBtn;
    private javax.swing.JPanel jpEliminarBtn;
    private javax.swing.JPanel jpGuardarBtn;
    private javax.swing.JPanel jpInscripciones;
    private javax.swing.JPanel jpMaterias;
    private javax.swing.JPanel jpMateriasbtn;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpNotas;
    private javax.swing.JPanel jpNotasbtn;
    private javax.swing.JPanel jpNuevoBtn;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JRadioButton jrbEstado;
    private javax.swing.JTable jtAlumnos;
    private javax.swing.JTextField jtAño;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTable jtMaterias;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTabbedPane jtpVentanas;
    // End of variables declaration//GEN-END:variables
    
    private void armarTablaMaterias(){
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Año");
        jtMaterias.setModel(modelo);
    }
    
    private void armarTablaAlumnos(){
        modelo2.addColumn("ID");
        modelo2.addColumn("DNI");
        modelo2.addColumn("Apellido");
        modelo2.addColumn("Nombre");
        jtAlumnos.setModel(modelo2);
    }
    
    private void cargarTablaMaterias(){
        for(Materia materia:lista){
            modelo.addRow(new Object[]{
                materia.getIdMateria(),
                materia.getNombre(),
                materia.getAnioMateria()
            });
        }
    }
}
