/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import java.sql.Date;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import universidadproject.AccesoADatos.AlumnoData;
import universidadproject.Entidades.Alumno;

/**
 *
 * @author kicho
 */
public class formularioAlumnos extends javax.swing.JInternalFrame {
    AlumnoData alumnoData = new AlumnoData();
    Alumno alumno = new Alumno();
    /**
     * Creates new form formularioAlumnos
     */
    public formularioAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPSalirBtn = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPNuevoBtn = new javax.swing.JPanel();
        jLNuevoBtn = new javax.swing.JLabel();
        jPEliminarBtn = new javax.swing.JPanel();
        jLEliminarBtn = new javax.swing.JLabel();
        jPGuardarBtn = new javax.swing.JPanel();
        jLGuardarBtn = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLSalirBtn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtDocumento = new javax.swing.JTextField();
        jPBuscarBtn = new javax.swing.JPanel();
        jLBuscarBtn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRbEstado = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jDCfechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();

        jPSalirBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPSalirBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPNuevoBtn.setBackground(new java.awt.Color(0, 51, 153));
        jPNuevoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPNuevoBtnMouseClicked(evt);
            }
        });

        jLNuevoBtn.setText("Nuevo");

        javax.swing.GroupLayout jPNuevoBtnLayout = new javax.swing.GroupLayout(jPNuevoBtn);
        jPNuevoBtn.setLayout(jPNuevoBtnLayout);
        jPNuevoBtnLayout.setHorizontalGroup(
            jPNuevoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNuevoBtnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLNuevoBtn)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPNuevoBtnLayout.setVerticalGroup(
            jPNuevoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPNuevoBtnLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLNuevoBtn)
                .addContainerGap())
        );

        jPEliminarBtn.setBackground(new java.awt.Color(0, 51, 153));
        jPEliminarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPEliminarBtnMouseClicked(evt);
            }
        });

        jLEliminarBtn.setText("Eliminar");

        javax.swing.GroupLayout jPEliminarBtnLayout = new javax.swing.GroupLayout(jPEliminarBtn);
        jPEliminarBtn.setLayout(jPEliminarBtnLayout);
        jPEliminarBtnLayout.setHorizontalGroup(
            jPEliminarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEliminarBtnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLEliminarBtn)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPEliminarBtnLayout.setVerticalGroup(
            jPEliminarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEliminarBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLEliminarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPGuardarBtn.setBackground(new java.awt.Color(0, 51, 153));
        jPGuardarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPGuardarBtnMouseClicked(evt);
            }
        });

        jLGuardarBtn.setText("Guardar");

        javax.swing.GroupLayout jPGuardarBtnLayout = new javax.swing.GroupLayout(jPGuardarBtn);
        jPGuardarBtn.setLayout(jPGuardarBtnLayout);
        jPGuardarBtnLayout.setHorizontalGroup(
            jPGuardarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGuardarBtnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLGuardarBtn)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPGuardarBtnLayout.setVerticalGroup(
            jPGuardarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPGuardarBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLGuardarBtn)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(0, 51, 153));

        jLSalirBtn.setText("Salir");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLSalirBtn)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLSalirBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPNuevoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPEliminarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPGuardarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPGuardarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPEliminarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPNuevoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPSalirBtn.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 340, -1));

        jLabel1.setText("Documento");

        jTxtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDocumentoActionPerformed(evt);
            }
        });

        jPBuscarBtn.setBackground(new java.awt.Color(0, 102, 153));
        jPBuscarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPBuscarBtnMouseClicked(evt);
            }
        });

        jLBuscarBtn.setText("Buscar");

        javax.swing.GroupLayout jPBuscarBtnLayout = new javax.swing.GroupLayout(jPBuscarBtn);
        jPBuscarBtn.setLayout(jPBuscarBtnLayout);
        jPBuscarBtnLayout.setHorizontalGroup(
            jPBuscarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBuscarBtnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLBuscarBtn)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPBuscarBtnLayout.setVerticalGroup(
            jPBuscarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBuscarBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLBuscarBtn)
                .addContainerGap())
        );

        jLabel2.setText("Apellido");

        jLabel3.setText("Nombre");

        jLabel4.setText("Estado");

        jRbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbEstadoActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha de Nacimiento");

        jLabel6.setText("Alumno");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(86, 86, 86)
                        .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(94, 94, 94)
                        .addComponent(jRbEstado))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jDCfechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTxtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jPBuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPBuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addComponent(jTxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jRbEstado))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5))
                    .addComponent(jDCfechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPSalirBtn.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 370, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPSalirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPSalirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDocumentoActionPerformed

    private void jPBuscarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPBuscarBtnMouseClicked
        try{
        String documento = jTxtDocumento.getText();
        alumno = alumnoData.buscarAlumnoPorDNI(Integer.parseInt(documento));
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "debe ingresar un numero valid");
        }
        jTxtApellido.setText(alumno.getApellido());
        jTxtNombre.setText(alumno.getNombre());
        jRbEstado.setSelected(alumno.getEstado());
        jDCfechaNacimiento.setDate(Date.valueOf(alumno.getFechaNac()));
    }//GEN-LAST:event_jPBuscarBtnMouseClicked

    private void jRbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRbEstadoActionPerformed

    private void jPNuevoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPNuevoBtnMouseClicked
        
        alumno = new Alumno();
        
        alumno.setDni(Integer.parseInt(jTxtDocumento.getText()));
        alumno.setApellido(jTxtApellido.getText());
        alumno.setNombre(jTxtNombre.getText());
        alumno.setFechaNac(jDCfechaNacimiento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        alumno.setEstado(true);
        
        alumnoData.guardarAlumno(alumno);
        //JOptionPane.showMessageDialog(null, "Alumno Agregado con exito!");
        
    }//GEN-LAST:event_jPNuevoBtnMouseClicked

    private void jPEliminarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPEliminarBtnMouseClicked
        if (jTxtDocumento.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe buscar un alumno para eliminarlo de la lista");
        }else{
            Alumno alumno = alumnoData.buscarAlumnoPorDNI(Integer.parseInt(jTxtDocumento.getText()));
            alumnoData.eliminarAlumno(alumno.getIdAlumno());
            JOptionPane.showMessageDialog(null, "El alumno fue dado de baja");
            
        }
    }//GEN-LAST:event_jPEliminarBtnMouseClicked

    private void jPGuardarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPGuardarBtnMouseClicked
        //Alumno alumno = alumnoData.buscarAlumnoPorDNI(Integer.parseInt(jTxtDocumento.getText()));
        if(jTxtDocumento.getText().isEmpty()||jTxtApellido.getText().isEmpty()||jTxtNombre.getText().isEmpty()||jDCfechaNacimiento.getDate().toString().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos para guardar");
        }else{
        alumno.setDni(Integer.parseInt(jTxtDocumento.getText()));
        alumno.setApellido(jTxtApellido.getText());
        alumno.setNombre(jTxtNombre.getText());
        alumno.setFechaNac(jDCfechaNacimiento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        alumnoData.modificarAlumno(alumno);
        }
    }//GEN-LAST:event_jPGuardarBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDCfechaNacimiento;
    private javax.swing.JLabel jLBuscarBtn;
    private javax.swing.JLabel jLEliminarBtn;
    private javax.swing.JLabel jLGuardarBtn;
    private javax.swing.JLabel jLNuevoBtn;
    private javax.swing.JLabel jLSalirBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPBuscarBtn;
    private javax.swing.JPanel jPEliminarBtn;
    private javax.swing.JPanel jPGuardarBtn;
    private javax.swing.JPanel jPNuevoBtn;
    private javax.swing.JPanel jPSalirBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRbEstado;
    private javax.swing.JTextField jTxtApellido;
    private javax.swing.JTextField jTxtDocumento;
    private javax.swing.JTextField jTxtNombre;
    // End of variables declaration//GEN-END:variables
}
