/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import java.sql.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import universidadproject.AccesoADatos.AlumnoData;
import universidadproject.Entidades.Alumno;

/**
 *
 * @author kicho
 */
public class formularioAlumnos extends javax.swing.JInternalFrame {
    AlumnoData alumnoData = new AlumnoData();
    /**
     * Creates new form formularioAlumnos
     */
    public formularioAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPSalirBtn = new javax.swing.JPanel();
        jRbEstado = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jDCfechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jTxtDocumento = new javax.swing.JTextField();
        jTxtApellido = new javax.swing.JTextField();
        jTxtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPBuscarBtn = new javax.swing.JPanel();
        jLBuscarBtn = new javax.swing.JLabel();
        jPNuevoBtn = new javax.swing.JPanel();
        jLNuevoBtn = new javax.swing.JLabel();
        jPGuardarBtn = new javax.swing.JPanel();
        jLGuardarBtn = new javax.swing.JLabel();
        jPEliminarBtn = new javax.swing.JPanel();
        jLEliminarBtn = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLSalirBtn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jPSalirBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbEstadoActionPerformed(evt);
            }
        });
        jPSalirBtn.add(jRbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        jLabel5.setText("Fecha de Nacimiento");
        jPSalirBtn.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));
        jPSalirBtn.add(jDCfechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        jLabel4.setText("Estado");
        jPSalirBtn.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 266, -1, 10));

        jTxtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDocumentoActionPerformed(evt);
            }
        });
        jPSalirBtn.add(jTxtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 130, -1));
        jPSalirBtn.add(jTxtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 130, -1));
        jPSalirBtn.add(jTxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 130, -1));

        jLabel1.setText("Documento");
        jPSalirBtn.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel2.setText("Apellido");
        jPSalirBtn.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel3.setText("Nombre");
        jPSalirBtn.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 10));

        jPBuscarBtn.setBackground(new java.awt.Color(0, 102, 153));
        jPBuscarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPBuscarBtnMouseClicked(evt);
            }
        });

        jLBuscarBtn.setText("Buscar");

        javax.swing.GroupLayout jPBuscarBtnLayout = new javax.swing.GroupLayout(jPBuscarBtn);
        jPBuscarBtn.setLayout(jPBuscarBtnLayout);
        jPBuscarBtnLayout.setHorizontalGroup(
            jPBuscarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBuscarBtnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLBuscarBtn)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPBuscarBtnLayout.setVerticalGroup(
            jPBuscarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBuscarBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLBuscarBtn)
                .addContainerGap())
        );

        jPSalirBtn.add(jPBuscarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, 26));

        jPNuevoBtn.setBackground(new java.awt.Color(0, 51, 153));
        jPNuevoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPNuevoBtnMouseClicked(evt);
            }
        });

        jLNuevoBtn.setText("Nuevo");

        javax.swing.GroupLayout jPNuevoBtnLayout = new javax.swing.GroupLayout(jPNuevoBtn);
        jPNuevoBtn.setLayout(jPNuevoBtnLayout);
        jPNuevoBtnLayout.setHorizontalGroup(
            jPNuevoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNuevoBtnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLNuevoBtn)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPNuevoBtnLayout.setVerticalGroup(
            jPNuevoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPNuevoBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLNuevoBtn)
                .addContainerGap())
        );

        jPSalirBtn.add(jPNuevoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, 30));

        jPGuardarBtn.setBackground(new java.awt.Color(0, 51, 153));

        jLGuardarBtn.setText("Guardar");

        javax.swing.GroupLayout jPGuardarBtnLayout = new javax.swing.GroupLayout(jPGuardarBtn);
        jPGuardarBtn.setLayout(jPGuardarBtnLayout);
        jPGuardarBtnLayout.setHorizontalGroup(
            jPGuardarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGuardarBtnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLGuardarBtn)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPGuardarBtnLayout.setVerticalGroup(
            jPGuardarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPGuardarBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLGuardarBtn)
                .addContainerGap())
        );

        jPSalirBtn.add(jPGuardarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        jPEliminarBtn.setBackground(new java.awt.Color(0, 51, 153));
        jPEliminarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPEliminarBtnMouseClicked(evt);
            }
        });

        jLEliminarBtn.setText("Eliminar");

        javax.swing.GroupLayout jPEliminarBtnLayout = new javax.swing.GroupLayout(jPEliminarBtn);
        jPEliminarBtn.setLayout(jPEliminarBtnLayout);
        jPEliminarBtnLayout.setHorizontalGroup(
            jPEliminarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEliminarBtnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLEliminarBtn)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPEliminarBtnLayout.setVerticalGroup(
            jPEliminarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEliminarBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLEliminarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPSalirBtn.add(jPEliminarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, 30));

        jPanel6.setBackground(new java.awt.Color(0, 51, 153));

        jLSalirBtn.setText("Salir");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLSalirBtn)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLSalirBtn)
                .addContainerGap())
        );

        jPSalirBtn.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 60, -1));

        jLabel6.setText("Alumno");
        jPSalirBtn.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPSalirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPSalirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDocumentoActionPerformed

    private void jPBuscarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPBuscarBtnMouseClicked
        Alumno alumno = new Alumno();
        String documento = jTxtDocumento.getText();
        alumno = alumnoData.buscarAlumnoPorDNI(Integer.parseInt(documento));

        jTxtApellido.setText(alumno.getApellido());
        jTxtNombre.setText(alumno.getNombre());
        jRbEstado.setSelected(alumno.getEstado());
        jDCfechaNacimiento.setDate(Date.valueOf(alumno.getFechaNac()));
    }//GEN-LAST:event_jPBuscarBtnMouseClicked

    private void jRbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRbEstadoActionPerformed

    private void jPNuevoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPNuevoBtnMouseClicked
        
        Alumno alumno = new Alumno();
        
        alumno.setDni(Integer.parseInt(jTxtDocumento.getText()));
        alumno.setApellido(jTxtApellido.getText());
        alumno.setNombre(jTxtNombre.getText());
        alumno.setFechaNac(jDCfechaNacimiento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        alumno.setEstado(true);
        
        alumnoData.guardarAlumno(alumno);
        JOptionPane.showMessageDialog(null, "Alumno Agregado con exito!");
        
    }//GEN-LAST:event_jPNuevoBtnMouseClicked

    private void jPEliminarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPEliminarBtnMouseClicked
        if (jTxtDocumento.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe buscar un alumno para eliminarlo de la lista");
        }else{
            Alumno alumno = alumnoData.buscarAlumnoPorDNI(Integer.parseInt(jTxtDocumento.getText()));
            alumnoData.eliminarAlumno(alumno.getIdAlumno());
            JOptionPane.showMessageDialog(null, "El alumno fue dado de baja");
            
        }
    }//GEN-LAST:event_jPEliminarBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDCfechaNacimiento;
    private javax.swing.JLabel jLBuscarBtn;
    private javax.swing.JLabel jLEliminarBtn;
    private javax.swing.JLabel jLGuardarBtn;
    private javax.swing.JLabel jLNuevoBtn;
    private javax.swing.JLabel jLSalirBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPBuscarBtn;
    private javax.swing.JPanel jPEliminarBtn;
    private javax.swing.JPanel jPGuardarBtn;
    private javax.swing.JPanel jPNuevoBtn;
    private javax.swing.JPanel jPSalirBtn;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRbEstado;
    private javax.swing.JTextField jTxtApellido;
    private javax.swing.JTextField jTxtDocumento;
    private javax.swing.JTextField jTxtNombre;
    // End of variables declaration//GEN-END:variables
}
