/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JOptionPane;
import universidadproject.AccesoADatos.MateriaData;
import universidadproject.Entidades.Materia;

/**
 *
 * @author aldia
 */
public class formularioMaterias extends javax.swing.JInternalFrame {
    MateriaData materiaData = new MateriaData();
    /**
     * Creates new form formularioMaterias
     */
    public formularioMaterias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jrbEstado = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtAño = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jpBuscarBtn = new javax.swing.JPanel();
        jlBuscarBtn = new javax.swing.JLabel();
        jpNuevoBtn = new javax.swing.JPanel();
        jlNuevoBtn = new javax.swing.JLabel();
        jpEliminarBtn = new javax.swing.JPanel();
        jlEliminarBtn = new javax.swing.JLabel();
        jpGuardarBtn = new javax.swing.JPanel();
        jlGuardarBtn = new javax.swing.JLabel();
        jpSalirBtn = new javax.swing.JPanel();
        jlSalirBtn = new javax.swing.JLabel();

        jrbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEstadoActionPerformed(evt);
            }
        });

        jLabel4.setText("Estado:");

        jtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCodigoActionPerformed(evt);
            }
        });

        jLabel1.setText("Código:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Año:");

        jLabel6.setText("Materia");

        jpBuscarBtn.setBackground(new java.awt.Color(0, 102, 153));
        jpBuscarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpBuscarBtnMouseClicked(evt);
            }
        });

        jlBuscarBtn.setForeground(new java.awt.Color(255, 255, 255));
        jlBuscarBtn.setText("Buscar");

        javax.swing.GroupLayout jpBuscarBtnLayout = new javax.swing.GroupLayout(jpBuscarBtn);
        jpBuscarBtn.setLayout(jpBuscarBtnLayout);
        jpBuscarBtnLayout.setHorizontalGroup(
            jpBuscarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBuscarBtnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlBuscarBtn)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jpBuscarBtnLayout.setVerticalGroup(
            jpBuscarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlBuscarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jpNuevoBtn.setBackground(new java.awt.Color(0, 102, 153));
        jpNuevoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpNuevoBtnMouseClicked(evt);
            }
        });

        jlNuevoBtn.setForeground(new java.awt.Color(255, 255, 255));
        jlNuevoBtn.setText("Nuevo");

        javax.swing.GroupLayout jpNuevoBtnLayout = new javax.swing.GroupLayout(jpNuevoBtn);
        jpNuevoBtn.setLayout(jpNuevoBtnLayout);
        jpNuevoBtnLayout.setHorizontalGroup(
            jpNuevoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNuevoBtnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlNuevoBtn)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jpNuevoBtnLayout.setVerticalGroup(
            jpNuevoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlNuevoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jpEliminarBtn.setBackground(new java.awt.Color(0, 102, 153));
        jpEliminarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpEliminarBtnMouseClicked(evt);
            }
        });

        jlEliminarBtn.setForeground(new java.awt.Color(255, 255, 255));
        jlEliminarBtn.setText("Eliminar");

        javax.swing.GroupLayout jpEliminarBtnLayout = new javax.swing.GroupLayout(jpEliminarBtn);
        jpEliminarBtn.setLayout(jpEliminarBtnLayout);
        jpEliminarBtnLayout.setHorizontalGroup(
            jpEliminarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEliminarBtnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlEliminarBtn)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jpEliminarBtnLayout.setVerticalGroup(
            jpEliminarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlEliminarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jpGuardarBtn.setBackground(new java.awt.Color(0, 102, 153));
        jpGuardarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpGuardarBtnMouseClicked(evt);
            }
        });

        jlGuardarBtn.setForeground(new java.awt.Color(255, 255, 255));
        jlGuardarBtn.setText("Guardar");

        javax.swing.GroupLayout jpGuardarBtnLayout = new javax.swing.GroupLayout(jpGuardarBtn);
        jpGuardarBtn.setLayout(jpGuardarBtnLayout);
        jpGuardarBtnLayout.setHorizontalGroup(
            jpGuardarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGuardarBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlGuardarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
        );
        jpGuardarBtnLayout.setVerticalGroup(
            jpGuardarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlGuardarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jpSalirBtn.setBackground(new java.awt.Color(0, 102, 153));
        jpSalirBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpSalirBtnMouseClicked(evt);
            }
        });

        jlSalirBtn.setForeground(new java.awt.Color(255, 255, 255));
        jlSalirBtn.setText("Salir");

        javax.swing.GroupLayout jpSalirBtnLayout = new javax.swing.GroupLayout(jpSalirBtn);
        jpSalirBtn.setLayout(jpSalirBtnLayout);
        jpSalirBtnLayout.setHorizontalGroup(
            jpSalirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSalirBtnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlSalirBtn)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jpSalirBtnLayout.setVerticalGroup(
            jpSalirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlSalirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(80, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jrbEstado)
                                    .addComponent(jtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)
                                        .addComponent(jpBuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jpNuevoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpEliminarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpGuardarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpSalirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpBuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jrbEstado)))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpNuevoBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpEliminarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jpGuardarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpSalirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbEstadoActionPerformed

    private void jtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCodigoActionPerformed

    private void jpBuscarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBuscarBtnMouseClicked
        Materia materia = new Materia();
        String codigo = jtCodigo.getText();
        try{
        materia = materiaData.buscarMateria(Integer.parseInt(codigo));
        jtNombre.setText(materia.getNombre());
        jtAño.setText(String.valueOf(materia.getAnioMateria()));
        jrbEstado.setSelected(materia.isActivo());
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(null, "La materia está dada de baja");
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "El código ingresado no es válido");
        }
    }//GEN-LAST:event_jpBuscarBtnMouseClicked

    private void jpNuevoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpNuevoBtnMouseClicked
        // TODO add your handling code here:
        Materia materia = new Materia();
        if(jtCodigo.getText().isEmpty() || jtNombre.getText().isEmpty() || jtAño.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "No debe haber campos vacíos"); 
        }else{
        try{
        materia.setIdMateria(Integer.parseInt(jtCodigo.getText()));
        materia.setNombre(jtNombre.getText());
        materia.setAnioMateria(Integer.parseInt(jtAño.getText()));
        materia.setActivo(true);
        materiaData.guardarMateria(materia);
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(null, "No debe haber campos vacíos");
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "El código ingresado no es válido");
        }
        }
        jtCodigo.setText("");
        jtNombre.setText("");
        jtAño.setText("");
        jrbEstado.setSelected(false);
    }//GEN-LAST:event_jpNuevoBtnMouseClicked

    private void jpEliminarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpEliminarBtnMouseClicked
        // TODO add your handling code here:
        String codigo = jtCodigo.getText();
        try{
        materiaData.eliminarMateria(Integer.parseInt(codigo));
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "El código ingresado no es válido");
        }
    }//GEN-LAST:event_jpEliminarBtnMouseClicked

    private void jpGuardarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpGuardarBtnMouseClicked
        // TODO add your handling code here:
        Materia materia = new Materia();
        if(jtCodigo.getText().isEmpty() || jtNombre.getText().isEmpty() || jtAño.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "No debe haber campos vacíos"); 
        }else{
        try{
        materia.setIdMateria(Integer.parseInt(jtCodigo.getText()));
        materia.setNombre(jtNombre.getText());
        materia.setAnioMateria(Integer.parseInt(jtAño.getText()));
        materia.setActivo(true);
        materiaData.modificarMateria(materia);
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(null, "No debe haber campos vacíos");
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "El código ingresado no es válido");
        }
        }
    }//GEN-LAST:event_jpGuardarBtnMouseClicked

    private void jpSalirBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpSalirBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jpSalirBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlBuscarBtn;
    private javax.swing.JLabel jlEliminarBtn;
    private javax.swing.JLabel jlGuardarBtn;
    private javax.swing.JLabel jlNuevoBtn;
    private javax.swing.JLabel jlSalirBtn;
    private javax.swing.JPanel jpBuscarBtn;
    private javax.swing.JPanel jpEliminarBtn;
    private javax.swing.JPanel jpGuardarBtn;
    private javax.swing.JPanel jpNuevoBtn;
    private javax.swing.JPanel jpSalirBtn;
    private javax.swing.JRadioButton jrbEstado;
    private javax.swing.JTextField jtAño;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables
}
